import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    padding: 18,
    backgroundColor: '#FFFFFF',
  },
  wrapperHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  wrapperBack: {
    flexDirection: 'row',
    marginTop: 10,
  },
  addVehicle: {
    marginLeft: 24,
    fontSize: 20,
    fontFamily: 'Nunito-Bold',
    // justifyContent: 'flex-start',
  },
  cancel: {
    // marginLeft: 24,
    marginTop: 10,
    fontSize: 20,
    fontFamily: 'Nunito-Bold',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    color: '#B8BECD',
  },
  wrapperCamera: {
    alignItems: 'center',
    marginTop: 60,
  },
  iconCamera: {
    marginBottom: 50,
  },
  button: {
    backgroundColor: '#393939',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
    padding: 15,
    marginTop: 100,
    bottom: 70,
    width: '50%',
  },
  buttonText: {
    color: '#FFCD61',
    fontFamily: 'Nunito-Bold',
    fontSize: 14,
  },
  wrapperInput: {
    marginTop: 0,
    bottom: 50,
  },
  textInput: {
    textAlign: 'center',
    borderBottomWidth: 1,
    borderColor: '#B8B8B8',
    borderRadius: 8,
    width: '100%',
    padding: 16,
    backgroundColor: 'transparent',
    color: 'black',
    fontFamily: 'Nunito-Regular',
  },
  wrapperInputLeft: {
    marginTop: 5,
  },
  label: {
    color: '#393939',
    fontWeight: '600',
    fontFamily: 'Nunito-Bold',
    fontSize: 17,
  },
  textInputLeft: {
    textAlign: 'left',
    borderBottomWidth: 1,
    borderColor: '#B8B8B8',
    borderRadius: 8,
    width: '100%',
    backgroundColor: 'transparent',
    color: 'black',
    fontFamily: 'Nunito-Regular',
  },
  labelSelect: {
    color: '#393939',
    fontWeight: '600',
    fontFamily: 'Nunito-Bold',
    fontSize: 17,
    marginTop: 20,
  },
  textInputWithBorder: {
    textAlign: 'left',
    borderWidth: 1,
    borderColor: '#B8B8B8',
    borderRadius: 8,
    width: '100%',
    backgroundColor: 'transparent',
    color: 'black',
    marginVertical: 10,
  },
  inputSelect: {
    borderWidth: 1,
  },
  wrapperSelect: {
    marginTop: 13,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  textAmount: {
    color: '#393939',
    fontSize: 16,
    fontFamily: 'Nunito-Bold',
  },
  available: {
    backgroundColor: '#FFCD61',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 4,
    height: 25,
    width: 26,
  },
  amount: {
    color: 'black',
    fontWeight: 'bold',
    fontSize: 18,
  },
  buttonSave: {
    backgroundColor: '#FFCD61',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
    padding: 13,
    marginTop: 50,
  },
  buttonTextSave: {
    color: 'black',
    fontSize: 18,
    fontFamily: 'Nunito-Bold',
  },
  vehicleImg: {
    width: 150,
    height: 150,
    borderRadius: 100,
  },
});
